CREATE TABLE PERSONS(
ID BIGINT IDENTITY NOT NULL PRIMARY KEY,
NAME VARCHAR(100)
);

CREATE TABLE RECIPES(
ID BIGINT IDENTITY NOT NULL PRIMARY KEY,
TITLE VARCHAR(100) NOT NULL,
PERSON_ID BIGINT NOT NULL,
INGR VARCHAR(100) NOT NULL,
DESCRIPTION VARCHAR(100) NOT NULL,
FOREIGN KEY (PERSON_ID) REFERENCES PERSONS(ID)
);

CREATE TABLE COMMENTS(
ID BIGINT IDENTITY NOT NULL PRIMARY KEY,
RECIPE_ID BIGINT NOT NULL,
COM_AUTHOR_ID BIGINT NOT NULL,
TEXT VARCHAR(100) NOT NULL
);

----------------------------------------------------------------
-- SECURITY
----------------------------------------------------------------
CREATE TABLE USERS(
ID BIGINT IDENTITY NOT NULL PRIMARY KEY,
PASSWORD VARCHAR(100) NOT NULL,
USERNAME VARCHAR(100) NOT NULL
);

CREATE TABLE ROLES(
ID BIGINT IDENTITY NOT NULL PRIMARY KEY,
ROLE VARCHAR(20) NOT NULL
);

CREATE TABLE USER_ROLE(
USER_ID BIGINT NOT NULL,
ROLE_ID BIGINT NOT NULL,
FOREIGN KEY (USER_ID) REFERENCES USERS(ID),
FOREIGN KEY (ROLE_ID) REFERENCES ROLES(ID)
);
